### ISSUE TITLE
AccountID?

### ISSUE THREAD

**Issue by darrenhillconsulting** [ExploreConsulting/netsuite-sync#5]
Should I not have to specify an AccountID some where?  My credentials give me access to lots of Netsuite instances.

**Comment by ShawnTalbert** [comment]
when you run `ns -g` it should interactively list all the accounts and roles you have. You select from the menu and it should take care of accountid and role settings. `ns -g` is the way to get started with a new project/client/folder.

**Comment by darrenhillconsulting** [comment]
I see, makes sense.  Then I think I've found a different bug then.  I never get to the 'list'.  I get a

`items` must be Array (max length: 35).

After I select 'n' for Sandbox Account? (y/n)

**Comment by ShawnTalbert** [comment]
Hah. I think you've hit the limit of the menu generation library. You might want to edit your NetSuiteConfig.js manually then encrypt it with `ns -e`. You can create a template NetSuiteConfig.js with `ns -c > NetSuiteConfig.js`

p.s., on an unrelated note, have you considered the security implications of having your single login credentials tied to so many accounts/roles? I strive to have the absolute minimum NetSuite accounts associated with my login so that compromise of my password won't compromise a bunch of different NS accounts...

**Comment by ShawnTalbert** [comment]
Plan would be to look towards switching menuing libraries or modifying the one we're using.
